openapi: 3.0.0
info:
  title: ID Generation API
  description: API for generating and retrieving Identities with system-agnostic unique identifiers.
  version: 0.0.1

paths:
  /ids:
    post:
      summary: Generate new IDs
      description: Creates and returns globally unique Identities in the format `{Display ID}-{Complement ID}-Version`.
      operationId: createID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                count:
                  type: integer
                  description: "Number of IDs to generate."
                  example: 5
                version:
                  type: integer
                  description: "Version of the SOIM format to be used for identity."
                  example: 1
              required:
                - count
                - version
      responses:
        '200':
          description: Successful generation of IDs
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  ids:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: "Full SOIM format ID."
                          example: "643603667651-1S1334GYRSJMZVJ38W-1"
                        displayID:
                          type: string
                          description: "Display part of the ID, human-readable."
                          example: "643603667651"
                        complementID:
                          type: string
                          description: "Complement part of the ID, machine-readable."
                          example: "1S1334GYRSJMZVJ38W"
                        version:
                          type: integer
                          description: "Version of the ID format."
                          example: 1
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Invalid parameters in request"

    get:
      summary: Retrieve last created ID
      description: Returns the details of the last created Identity.
      operationId: getLastID
      responses:
        '200':
          description: Successful retrieval of last created ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  lastID:
                    type: object
                    properties:
                      id:
                        type: string
                        description: "Full SOIM format ID."
                        example: "003914737010-09I1NRTQYUJDZTWJC9-1"
                      displayID:
                        type: string
                        description: "Display part of the ID, human-readable."
                        example: "003914737010"
                      complementID:
                        type: string
                        description: "Complement part of the ID, machine-readable."
                        example: "09I1NRTQYUJDZTWJC9"
                      version:
                        type: integer
                        description: "Version of the ID format."
                        example: 1
        '404':
          description: No IDs found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "No IDs have been created yet."

components:
  schemas:
    ID:
      type: object
      properties:
        id:
          type: string
          description: "Full format ID"